apiVersion: v1
kind: LimitRange
metadata:
  name: webapp-limits
spec:
  limits:
  - default:
      cpu: 200m
      memory: 500Mi
    defaultRequest:
      cpu: 200m
      memory: 500Mi
    max:
      cpu: "1"
      memory: 1Gi
    min:
      cpu: 100m
      memory: 200Mi
    type: Container